date = 2021-11-08
texte = "la HAS recommande de privilégier le vaccin Pfizer pour les moins de 30 ans"
lien = "/je-veux-me-faire-vacciner.html#quel-est-le-vaccin-administre-pour-la-dose-de-rappel-dite-3-e-dose"
emoji = "💉"
