date = 2021-11-25
texte = "le rappel vaccinal sera ouvert à toutes les personnes de 18 ans et plus, dès 5 mois après la dernière injection ou la dernière infection à la Covid, à compter du samedi 27 novembre"
lien = "je-veux-me-faire-vacciner.html#suis-je-concerne-par-la-dose-de-rappel-dite-3-e-dose"
emoji = "💉"
