date = 2021-11-29
texte = "la durée de validité des tests PCR et antigéniques négatifs est réduite à 24 h pour le pass sanitaire"
lien = "pass-sanitaire-qr-code-voyages.html#qu-est-ce-que-le-pass-sanitaire"
emoji = "🛂"
