date = 2021-12-28
texte = "le rappel vaccinal est possible dès 3 mois après la dernière injection ou la dernière infection à la Covid"
lien = "je-veux-me-faire-vacciner.html#a-partir-de-quand-pourrai-je-recevoir-la-dose-de-rappel-dite-3-e-dose"
emoji = "💉"
