date = 2021-11-09
texte = "à partir du 15 décembre, le pass sanitaire sera conditionné à une dose de rappel pour les plus de 65 ans et les vaccinés Janssen"
lien = "/je-veux-me-faire-vacciner.html#est-ce-que-la-dose-de-rappel-dite-3-e-dose-est-obligatoire-pour-le-pass-sanitaire"
emoji = "🛂"
