date = 2021-11-23
texte = "la vaccination contre la grippe saisonnière est maintenant ouverte à toute la population, et peut-être couplée à la dose de rappel contre la Covid"
lien = "je-veux-me-faire-vacciner.html#puis-je-me-faire-vacciner-contre-la-grippe-saisonniere-et-la-covid-en-meme-temps"
emoji = "🦠"
