date = 2022-02-15
texte = "la dose de rappel doit être réalisée 3 à 4 mois après la vaccination initiale"
lien = "pass-sanitaire-qr-code-voyages.html#avant-quelle-date-dois-je-recevoir-la-dose-de-rappel-dite-3-e-dose-pour-conserver-mon-passe-vaccinal"
emoji = "💉"
