date = 2022-01-01
texte = "le port du masque est dorénavant obligatoire pour les enfants à partir de 6 ans dans certains lieux publics (gares et aéroports, transports collectifs, établissements recevant du public, marchés)"
lien = "conseils-pour-les-enfants.html"
emoji = "😷"
