date = 2022-02-15
texte = "la dose de rappel doit être réalisée 3 à 4 mois après la vaccination initiale"
lien = "pass-sanitaire-qr-code-voyages.html#quand-dois-je-recevoir-mon-rappel-pour-conserver-mon-passe-sanitaire"
emoji = "💉"
