date = 2022-03-14
texte = "fin du passe vaccinal, mais le passe sanitaire reste requis dans certains lieux"
lien = "pass-sanitaire-qr-code-voyages.html#dans-quels-lieux-le-passe-sanitaire-est-il-demande"
emoji = "🛂"
