date = 2022-01-03
texte = "la durée d’isolement des personnes positives ET vaccinées est réduite à 7 jours"
lien = "j-ai-des-symptomes-covid.html#que-faire-si-j-ai-des-symptomes-et-ou-que-je-suis-positif"
emoji = "⏳"
