date = 2022-01-24
texte = "ouverture du rappel vaccinal aux adolescent(e)s de 12 à 17 ans"
lien = "pass-sanitaire-qr-code-voyages.html#avant-quelle-date-dois-je-recevoir-la-dose-de-rappel-dite-3-e-dose-pour-conserver-mon-passe-vaccinal"
emoji = "💉"
