graph TD
    introduction(("Page d’accueil")) -->|pour moi| symptomes
    introduction(("Page d’accueil")) -->|pour un proche| nom

    nom("Nom ?") --> symptomes

    symptomes("1/5 Mon état actuel")
    symptomes ---->|"symptômes actuels"| depistage
    symptomes ---->|"symptômes passés"| depistage
    symptomes -->|"pas de symptômes"| contactarisque

    contactarisque("2/5 Mes contacts récents")
    contactarisque -->|"contact à risque"| depistage
    contactarisque -->|"ok"| depistage

    depistage("3/5 Test Covid ?")
    depistage --->|pas de test| situation
    depistage --->|positif| situation
    depistage --->|négatif| situation
    depistage --->|en attente| situation

    situation("4/5 Situation") --> sante("5/5 Santé")

    sante --> conseils(("Conseils"))

    conseils -->|"Suivi"| suivisymptomes("L’évolution de mes symptômes")
