graph TD
    introduction(("Page d’accueil")) -->|pour moi| symptomesactuels
    introduction(("Page d’accueil")) -->|pour un proche| nom

    nom("Nom ?") --> symptomesactuels

    symptomesactuels("Symptômes actuels ?")
    symptomesactuels -->|"oui, lesquels ?"| debutsymptomes
    symptomesactuels -->|non| symptomespasses

    symptomespasses("Symptômes passés <= 7 jours ?")
    symptomespasses -->|oui| debutsymptomes
    symptomespasses -->|non| contactarisque

    debutsymptomes("Depuis quand ?")
    debutsymptomes -->|date| depistage

    contactarisque("Contact à risque ?")
    contactarisque -->|oui| depistage
    contactarisque -->|non| depistage

    depistage("Test Covid ?")
    depistage --->|pas de test| residence
    depistage --->|positif| residence
    depistage --->|négatif| residence
    depistage --->|en attente| residence

    subgraph Questions bonus
        residence("Résidence") --> foyer("Foyer") --> antecedents("Antécédents") --> caracteristiques("Caractéristiques") --> activitepro("Activité")
    end

    activitepro --> conseils(("Conseils"))

    conseils --> debutconnu

    subgraph Suivi
        debutconnu("Date de début connue")
        debutconnu -->|oui| suivisymptomes
        debutconnu -->|non| debutsymptomes2

        debutsymptomes2("Depuis quand ?")
        debutsymptomes2 --> suivisymptomes
    end
