graph LR
    suivi{{"Suivi des<br>symptômes<br>démarré ?"}}
    suivi --->|oui| gravite-3
    suivi --->|non| symptomes-actuels

    subgraph Suivi
        gravite-3{{"Aggravation forte<br>du souffle ou<br>de l&rsquo;état général"}}
        gravite-3 ------->|oui| suivi-gravite-3
        gravite-3 -->|non| gravite-2

        gravite-2{{"Aggravation du souffle<br>ou de l&rsquo;état général,<br>confusion,<br>impossibilité de boire<br> ou de s&rsquo;alimenter,<br>ou maux de tête"}}
        gravite-2 ------>|oui| suivi-gravite-2
        gravite-2 -->|non| gravite-1

        gravite-1{{"Fièvre,<br>diarrhée,<br>vomissements,<br>ou toux"}}
        gravite-1 ----->|oui| suivi-gravite-1
        gravite-1 ----->|non| suivi-gravite-0
    end

    subgraph Orientation

        situation -->|"symptômes actuels"| facteurs-de-gravite-majeurs
        situation -->|"symptômes passés"| depistage-symptomes-passes
        situation -->|"contact à risque"| statut-contact-a-risque
        situation -->|"rien de tout ça"| personne-fragile

        facteurs-de-gravite-majeurs{{"Facteurs<br>de gravité<br>majeurs ?"}}
        facteurs-de-gravite-majeurs -->|oui| depistage-avec-gravite-majeure
        facteurs-de-gravite-majeurs -->|non| depistage-avec-symptomes

        depistage-avec-gravite-majeure{{"Résultat de test ?"}}
        depistage-avec-gravite-majeure ----->|positif| statut-positif-symptomatique-urgent
        depistage-avec-gravite-majeure ----->|negatif| statut-symptomatique-urgent
        depistage-avec-gravite-majeure ----->|en attente| statut-symptomatique-urgent
        depistage-avec-gravite-majeure ----->|pas testé| statut-symptomatique-urgent

        depistage-avec-symptomes{{"Résultat de test ?"}}
        depistage-avec-symptomes ----->|positif| statut-symptomatique-positif
        depistage-avec-symptomes ----->|negatif| statut-symptomatique-negatif
        depistage-avec-symptomes ----->|en attente| statut-symptomatique-en-attente
        depistage-avec-symptomes ----->|pas testé| statut-symptomatique-sans-test

        depistage-symptomes-passes{{Résultat de test ?}}
        depistage-symptomes-passes -->|positif| statut-symptomes-passes-positif
        depistage-symptomes-passes -->|en attente| statut-symptomes-passes-en-attente
        depistage-symptomes-passes -->|pas testé| statut-symptomes-passes-pas-teste
        depistage-symptomes-passes -->|negatif| personne-fragile

        %% depistage-sans-symptomes{{"Résultat de test ?"}}
        %% depistage-sans-symptomes ------>|positif| statut-asymptomatique
        %% depistage-sans-symptomes -->|autres cas| symptomes-passes

        %% symptomes-passes{{"Symptômes<br>passés ?"}}
        %% symptomes-passes -->|oui| depistage-symptomes-passes
        %% symptomes-passes -->|non| contact-a-risque

        personne-fragile{{"Personne<br>fragile ?"}}
        personne-fragile --->|oui| statut-personne-fragile
        personne-fragile -->|non| foyer-fragile

        foyer-fragile{{"Foyer<br>fragile ?"}}
        foyer-fragile -->|oui| statut-foyer-fragile
        foyer-fragile -->|non| statut-peu-de-risques
    end

    statut-positif-symptomatique-urgent["Appelle le 15 et dis que tu as la Covid + tes symptomes<br><br>statut_positif_symptomatique_urgent.md<br>conseils_personnels_symptômes_actuels_positif_critique.md"]
    statut-symptomatique-urgent["Appelle le 15 et dis tes symptomes, tu as peut-être la Covid<br><br>statut_symptomatique_urgent.md<br>conseils_personnels_symptômes_actuels_sans_depistage_critique.md"]

    statut-symptomatique-positif["Tu as la Covid (merci Cap. Obvious!), reste isolé et suis tes symptômes<br><br>statut_symptomatique_positif.md<br>+ conseils_personnels_depistage_positif_symptomatique.md"]
    statut-symptomatique-negatif["Tu n’as pas la Covid, mais appelle ton médecin pour tes symptômes<br><br>statut_symptomatique_négatif.md"]
    statut-symptomatique-en-attente["Reste chez toi en attendant le résultat<br><br>statut_symptomatique_en_attente.md<br>conseils_personnels_symptômes_actuels_en_attente.md"]
    statut-symptomatique-sans-test["Reste chez toi le temps de faire un test<br><br>statut_symptomatique.md<br>+ conseils_personnels_symptômes_actuels_sans_depistage.md"]

    statut-asymptomatique["Reste quand même chez toi<br><br>statut_asymptomatique.md<br>+ conseils_personnels_depistage_positif_asymptomatique.md"]

    statut-symptomes-passes-positif["Reste chez toi 7 jours après début des symptômes"]
    statut-symptomes-passes-en-attente["Reste chez toi 7 jours après début des symptômes et fais un test<br><br>statut_risque_élevé_contamination.md<br>conseils_personnels_symptômes_passés.md"]
    statut-symptomes-passes-pas-teste["Reste chez toi 7 jours après début des symptômes et fais un test<br><br>statut_risque_élevé_contamination.md<br>conseils_personnels_symptômes_passés.md"]

    statut-contact-a-risque["statut_risque_élevé_contamination.md"]
    statut-personne-fragile["statut_personne_fragile.md<br>+ conseils_personnels_symptômes_passés_avec_risques.md<br>+ conseils_personnels_symptômes_passés_avec_risques_info.md"]
    statut-foyer-fragile["statut_foyer_fragile.md"]
    statut-peu-de-risques["statut_peu_de_risques.md"]

    suivi-gravite-3["suivi_gravité_3.md"]
    suivi-gravite-2["suivi_gravité_2.md"]
    suivi-gravite-1["suivi_gravité_1.md"]
    suivi-gravite-0["suivi_gravité_0.md"]

    classDef default fill:#acf;
    classDef statut fill:#ffc;
    classDef statut-a-revoir fill:#eca;

    class suivi-gravite-3 statut;
    class suivi-gravite-2 statut;
    class suivi-gravite-1 statut;
    class suivi-gravite-0 statut;

    class statut-foyer-fragile statut;
    class statut-personne-fragile statut;
    class statut-peu-de-risques statut;
    class statut-symptomes-passes statut-a-revoir;
    class statut-contact-a-risque statut-a-revoir;
    class statut-asymptomatique statut;
    class statut-symptomatique-positif statut;
    class statut-symptomatique-negatif statut;
    class statut-symptomatique-en-attente statut;
    class statut-symptomatique-sans-test statut;
    class statut-symptomatique-urgent statut;
    class statut-positif-symptomatique-urgent statut;