name: Construire le site

on: push

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install French locale
        run: |
          sudo apt-get update
          sudo apt-get install locales-all
          sudo localectl set-locale LANG=fr_FR.utf8

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Set up Node v14
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Configure pip cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python dependencies
        run: |
          make install-python

      - name: Configure npm cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install JS dependencies
        run: |
          make install-js

      - name: Run linter
        run: |
          make lint

      - name: Run unit tests
        run: |
          npm run-script test:coverage

      - name: Run tools tests
        run: |
          make test-tools

      - name: Run feedback tests
        run: |
          make test-feedback

      - name: Check versions
        run: |
          make check-versions
        env:
          PYTHONUNBUFFERED: "1"

      - name: Check orphelins
        run: |
          make check-orphelins
        env:
          PYTHONUNBUFFERED: "1"

      - name: Check diagrammes
        run: |
          make check-diagrammes
        env:
          PYTHONUNBUFFERED: "1"

      - name: Check service-worker
        run: |
          make check-service-worker
        env:
          PYTHONUNBUFFERED: "1"

      - name: Check internal links
        run: |
          python3 build.py index thematiques
          make check-internal-links
        env:
          PYTHONUNBUFFERED: "1"

      - name: Check spelling
        run: |
          sudo apt-get install hunspell hunspell-fr
          make check-spelling

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'  # preserve history

      - name: Install French locale
        run: |
          sudo apt-get update
          sudo apt-get install locales-all
          sudo localectl set-locale LANG=fr_FR.utf8

      - name: Adjust file modification times based on commit author date
        run: |
          for FILE in $(git ls-files contenus/thematiques)
          do
              TIME=$(git log -n1 --date=iso --pretty=format:%ad -- "$FILE")
              touch -m --date="$TIME" "$FILE"
          done
          ls -l contenus/thematiques

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Set up Node v14
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Configure pip cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python dependencies
        run: |
          make install-python

      - name: Configure npm cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install JS dependencies
        run: |
          make install-js

      - name: Build
        run: |
          make build

      - name: Get Run ID for upload job
        id: upload_run_id
        run: |
          echo "::set-output name=RUN_ID::${{ github.run_id }}"

      - uses: actions/upload-artifact@v2
        with:
          name: mesconseilscovid-${{ env.GITHUB_REF_SLUG_URL }}-${{ env.GITHUB_SHA_SHORT }}
          path: dist/

  browser-tests:
    name: Browser tests
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        browser:
          - chromium
          - firefox
          - webkit
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install French locale
        run: |
          sudo apt-get update
          sudo apt-get install locales-all
          sudo localectl set-locale LANG=fr_FR.utf8

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x

      - name: Download build
        uses: actions/download-artifact@v2
        with:
          name: mesconseilscovid-${{ env.GITHUB_REF_SLUG_URL }}-${{ env.GITHUB_SHA_SHORT }}
          path: dist

      - name: Set up Node v14
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Set up Playwright
        uses: microsoft/playwright-github-action@v1

      - name: Configure npm cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install JS dependencies
        run: |
          make install-js

      - name: Download browser
        run: |
          npx playwright install "${{ matrix.browser }}"

      - name: Run browser tests
        run: |
          npm run-script test-integration:ci
        env:
          BROWSER: "${{ matrix.browser }}"
          DEBUG: "pw:api"

  deploy:
    name: Trigger deployment
    runs-on: ubuntu-latest
    needs:
      - checks
      - browser-tests
    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x

      - name: Check for write permission (our own PRs only, not forks or dependabot)
        id: check
        uses: scherermichael-oss/action-has-permission@master
        with:
          required-permission: write
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create deployment
        if: ${{ github.ref != 'refs/heads/master' && steps.check.outputs.has-permission }}
        uses: maxkomarychev/oction-create-deployment@v0.7.1
        id: create_deployment
        with:
          ref: ${{ github.ref }}
          environment: ${{ env.GITHUB_REF_SLUG_URL }}
          required_contexts: "<<EMPTY>>"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Send event to trigger deployment workflow
        if: steps.check.outputs.has-permission
        run: |
          OUTPUT_FILE=$(mktemp)
          HTTP_CODE=$(curl --silent --output $OUTPUT_FILE --write-out "%{http_code}" \
               -XPOST https://api.github.com/repos/Delegation-numerique-en-sante/mesconseilscovid-infra/dispatches \
               -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
               -H "Accept: application/vnd.github.everest-preview+json" \
               -H "Content-Type: application/json" \
               --data '{"event_type": "deploy", "client_payload": {"repo": "${{ github.repository }}", "commit": "${{ github.sha }}", "ref": "${{ github.ref }}", "slug": "${{ env.GITHUB_REF_SLUG_URL }}", "run_id": "${{ github.run_id }}", "artifact": "mesconseilscovid-${{ env.GITHUB_REF_SLUG_URL }}-${{ env.GITHUB_SHA_SHORT }}", "deployment_id": "${{ steps.create_deployment.outputs.id }}"}}')
          if [[ ${HTTP_CODE} -lt 200 || ${HTTP_CODE} -gt 299 ]] ; then
            >&2 cat $OUTPUT_FILE
            exit 1
          fi
          cat $OUTPUT_FILE
          rm $OUTPUT_FILE
