name: Construire le site

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v2.x

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install and build
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          make build

      - uses: actions/upload-artifact@v2
        with:
          name: mesconseilscovid-${{ env.GITHUB_REF_SLUG_URL }}
          path: dist/
