name: Construire le site

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v2.x

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Set up Node v14
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Set up Playwright
        uses: microsoft/playwright-github-action@v1

      - name: Install dependencies
        run: |
          make install

      - name: Build
        run: |
          make build

      - name: Run linter
        run: |
          make lint

      - name: Run unit tests
        run: |
          npm run-script test

      - name: Run browser tests (chromium)
        run: |
          npm run-script --browser=chromium test-integration
        env:
          DEBUG: "pw:api"

      - name: Run browser tests (firefox)
        run: |
          npm run-script --browser=firefox test-integration
        env:
          DEBUG: "pw:api"

      - name: Run browser tests (webkit)
        run: |
          npm run-script --browser=webkit test-integration
        env:
          DEBUG: "pw:api"

      - name: Check links
        run: |
          make check-links
        env:
          PYTHONUNBUFFERED: "1"

      - name: Check versions
        run: |
          make check-versions
        env:
          PYTHONUNBUFFERED: "1"

      - name: Check documentation
        run: |
          make check-documentation
        env:
          PYTHONUNBUFFERED: "1"

      - uses: actions/upload-artifact@v2
        with:
          name: mesconseilscovid-${{ env.GITHUB_REF_SLUG_URL }}-${{ env.GITHUB_SHA_SHORT }}
          path: dist/

      - name: Create deployment
        if: ${{ github.ref != 'refs/heads/master' }}
        uses: maxkomarychev/oction-create-deployment@v0.7.1
        id: create_deployment
        with:
          ref: ${{ github.ref }}
          environment: ${{ env.GITHUB_REF_SLUG_URL }}
          required_contexts: "<<EMPTY>>"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Send event to trigger deployment workflow
        if: ${{ github.ref != 'refs/heads/master' }}
        run: |
          curl -XPOST https://api.github.com/repos/Delegation-numerique-en-sante/mesconseilscovid-infra/dispatches \
               -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
               -H "Accept: application/vnd.github.everest-preview+json" \
               -H "Content-Type: application/json" \
               --data '{"event_type": "deploy", "client_payload": {"repo": "${{ github.repository }}", "commit": "${{ github.sha }}", "ref": "${{ github.ref }}", "slug": "${{ env.GITHUB_REF_SLUG_URL }}", "artifact": "mesconseilscovid-${{ env.GITHUB_REF_SLUG_URL }}-${{ env.GITHUB_SHA_SHORT }}", "deployment_id": "${{ steps.create_deployment.outputs.id }}"}}'
