name: Construire le site

on: push

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Set up Node v14
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Python dependencies
        run: |
          make install-python

      - name: Install JS dependencies
        run: |
          make install-js

      - name: Run linter
        run: |
          make lint

      - name: Run unit tests
        run: |
          npm run-script test:coverage

      - name: Run tools tests
        run: |
          make test-tools

      - name: Check versions
        run: |
          make check-versions
        env:
          PYTHONUNBUFFERED: "1"

      - name: Check orphelins
        run: |
          make check-orphelins
        env:
          PYTHONUNBUFFERED: "1"

      - name: Check diagrammes
        run: |
          make check-diagrammes
        env:
          PYTHONUNBUFFERED: "1"

      - name: Check service-worker
        run: |
          make check-service-worker
        env:
          PYTHONUNBUFFERED: "1"

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Set up Node v14
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Python dependencies
        run: |
          make install-python

      - name: Install JS dependencies
        run: |
          make install-js

      - name: Build
        run: |
          make build

      - uses: actions/upload-artifact@v2
        with:
          name: mesconseilscovid-${{ env.GITHUB_REF_SLUG_URL }}-${{ env.GITHUB_SHA_SHORT }}
          path: dist/

  browser-tests-chromium:
    name: Browser tests (Chromium)
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x

      - name: Download build
        uses: actions/download-artifact@v2
        with:
          name: mesconseilscovid-${{ env.GITHUB_REF_SLUG_URL }}-${{ env.GITHUB_SHA_SHORT }}
          path: dist

      - name: Set up Node v14
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Set up Playwright
        uses: microsoft/playwright-github-action@v1

      - name: Install JS dependencies
        run: |
          make install-js

      - name: Run browser tests (chromium)
        run: |
          npm run-script test-integration:ci
        env:
          BROWSER: "chromium"
          DEBUG: "pw:api"

  browser-tests-firefox:
    name: Browser tests (Firefox)
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x

      - name: Download build
        uses: actions/download-artifact@v2
        with:
          name: mesconseilscovid-${{ env.GITHUB_REF_SLUG_URL }}-${{ env.GITHUB_SHA_SHORT }}
          path: dist

      - name: Set up Node v14
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Set up Playwright
        uses: microsoft/playwright-github-action@v1

      - name: Install JS dependencies
        run: |
          make install-js

      - name: Run browser tests (firefox)
        run: |
          npm run-script test-integration:ci
        env:
          BROWSER: "firefox"
          DEBUG: "pw:api"

  browser-tests-webkit:
    name: Browser tests (WebKit)
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x

      - name: Download build
        uses: actions/download-artifact@v2
        with:
          name: mesconseilscovid-${{ env.GITHUB_REF_SLUG_URL }}-${{ env.GITHUB_SHA_SHORT }}
          path: dist

      - name: Set up Node v14
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Set up Playwright
        uses: microsoft/playwright-github-action@v1

      - name: Install JS dependencies
        run: |
          make install-js

      - name: Run browser tests (webkit)
        run: |
          npm run-script test-integration:ci
        env:
          BROWSER: "webkit"
          DEBUG: "pw:api"

  deploy:
    name: Trigger deployment
    runs-on: ubuntu-latest
    needs:
      - checks
      - browser-tests-chromium
      - browser-tests-firefox
      - browser-tests-webkit
    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x

      - name: Check for write permission (our own PRs only, not forks or dependabot)
        id: check
        uses: scherermichael-oss/action-has-permission@master
        with:
          required-permission: write
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create deployment
        if: ${{ github.ref != 'refs/heads/master' && steps.check.outputs.has-permission }}
        uses: maxkomarychev/oction-create-deployment@v0.7.1
        id: create_deployment
        with:
          ref: ${{ github.ref }}
          environment: ${{ env.GITHUB_REF_SLUG_URL }}
          required_contexts: "<<EMPTY>>"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Send event to trigger deployment workflow
        if: steps.check.outputs.has-permission
        run: |
          curl -XPOST https://api.github.com/repos/Delegation-numerique-en-sante/mesconseilscovid-infra/dispatches \
               -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
               -H "Accept: application/vnd.github.everest-preview+json" \
               -H "Content-Type: application/json" \
               --data '{"event_type": "deploy", "client_payload": {"repo": "${{ github.repository }}", "commit": "${{ github.sha }}", "ref": "${{ github.ref }}", "slug": "${{ env.GITHUB_REF_SLUG_URL }}", "artifact": "mesconseilscovid-${{ env.GITHUB_REF_SLUG_URL }}-${{ env.GITHUB_SHA_SHORT }}", "deployment_id": "${{ steps.create_deployment.outputs.id }}"}}'

  check-links:
    name: Check links
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Python dependencies
        run: |
          make install-python

      - name: Build index
        run: |
          python3 build.py index

      - name: Check links
        run: |
          make check-links
        env:
          PYTHONUNBUFFERED: "1"
