name: Vérifie que les liens externes sont toujours là

on:
  push:
  schedule:
    - cron: '30 7,13,19 * * *'

jobs:
  check-external-links:
    name: Check external links
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install French locale
        run: |
          sudo apt-get update
          sudo apt-get install locales-all
          sudo localectl set-locale LANG=fr_FR.utf8

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Configure pip cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python dependencies
        run: |
          make install-python

      - name: Build index
        run: |
          python3 build.py index

      - name: Check external links
        run: |
          make check-external-links
        env:
          PYTHONUNBUFFERED: "1"
