name: Optimiser les images

on:
  push:
    branches:
      - master

jobs:
  optimize-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PNG optimization tool
        run: |
          sudo apt-get install --yes zopfli

      - name: Optimize images
        run: |
          make optimize-images

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: Optimisation des images
          body: |
            Optimisation des images avec `zopflipng`.
          commit-message: Optimisation des images avec zopflipng
          branch: optimize-images
          delete-branch: true
