name: Optimiser les images

on:
  push:
    branches:
      - master

jobs:
  update-readme-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PNG optimization tool
        run: |
          apt install --yes optipng

      - name: Optimize images
        run: |
          make optimize-images

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: Optimisation des images
          body: |
            Optimisation des images avec `optipng`.
          commit-message: Optimisation des images
          branch: optimize-images
          delete-branch: true
