name: Mettre à jour les données quotidiennement

on:
  schedule:
    - cron: '15 11 * * *'

jobs:
  update-incidence:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Python dependencies
        run: |
          make install-python

      - name: Install Prettier
        run: |
          npm install prettier

      - name: Update incidence data
        run: |
          make incidence

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: Mise à jour des valeurs d’incidence
          body: |
            Mise jour automatique des valeurs d’incidence à partir des données
            publiées par Santé Publique France sur
            https://www.data.gouv.fr/fr/datasets/taux-dincidence-de-lepidemie-de-covid-19/
            (fichier CSV `sp-pe-std-quot-dep`)
          commit-message: Mise à jour des valeurs d’incidence
          branch: update-incidence
          delete-branch: true

  update-prefectures:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Python dependencies
        run: |
          make install-python

      - name: Install Prettier
        run: |
          npm install prettier

      - name: Update prefectures data
        run: |
          make prefectures

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: Mise à jour des liens vers les consignes préfectorales
          body: |
            Mise jour automatique des liens vers les consignes préfectorales
            publiés par le Service d’Information du Gouvernement sur
            https://www.data.gouv.fr/fr/datasets/liste-des-liens-url-redirigeant-vers-les-consignes-prefectorales-dans-le-cadre-du-covid-19/
          commit-message: Mise à jour des liens vers les consignes préfectorales
          branch: update-prefectures
          delete-branch: true
